Update coclustering.py
phenology/cgc pull request #23
Opened 2020-08-31 13:01 UTC by girgink

- Added private clean() method to reset error and number of runs completed, so that successive run_xxx() methods work properly. Otherwise they return immediately if previously calculated error is smaller than the threshold.

- Removed run_serial() method, which is not implemented and not in use.

- Removed self.client initialization in __init(). It is initialized in run_with_dask() anyway.

2020-09-01 09:38 UTC, fnattino requested changes
Hi @girgink, thanks for catching the issue with the initialisation of the clusters, this definitely needs to be fixed. Initializing them via the `run_xxx` methods instead of via a dedicated function sounds good to me.  

Now, I think that the cluster initialisation is not yet done properly in the `_dask_runs_memory` (the cluster assignment which is the result of a run is still used in the following run).
 
I also have some doubts about the variables initialised in the `_clean` method: I think to a user who wants to run the co-clustering algorithm but is unsure how many runs are sufficient to reach (or get close to) the global minimum. He could run:
```python
cc = Coclustering(Z, nruns=100)
cc.run_with_threads(nthreads=4)
# check value of cc.error
cc.run_with_threads(nthreads=4)
# check again value of cc.error: if it is lower than the previous value, run again cc.run_with_threads(4), otherwise stop here
```  
Or otherwise a user who wants to run the 'submit'-based Dask implementation, running a total of 100 runs divided in 4 batches:
```python
num_batches = 4
runs_per_batch = 25
cc = Coclustering(Z, nruns=runs_per_batch)
for b in range(num_batches):
    cc.run_with_dask()
```
For these examples `self.error` needs not to be initialised to `None` every time `run_with_xxx` is called, nor `self.nruns_completed` needs to be set to zero (it keeps track of the total, aggregated, number of runs that have been performed).

2020-09-01 10:02 UTC, fnattino commented
What about the following:

```python
class Coclustering(object):
  def __init__(...):
        ...
        self.row_clusters = None # initialize these variables in the init, remove _clean function
        self.col_clusters = None
        self.error = None
        self.nruns_completed = 0
```
Then:
```python
  def run_with_dask(self, ..., row_clusters=None, col_clusters=None):
    if low_memory:
      self._dask_runs_memory(row_clusters, col_clusters) # pass initial clusters as arguments
    else:
      self._dask_runs_performance(row_clusters, col_clusters)
```
```python
  def _dask_runs_memory(self, row_clusters=None, col_clusters=None):
    ...
    for r in range(self.nruns):
      converged, niters, row, col, e = coclustering_dask.coclustering(
        row_clusters_init=row_clusters,  # initialize cluster with input arguments 
        col_clusters_init=col_clusters
      )
    ...
    if self.error is None or e < self.error:
      self.row_clusters = row.compute() # store final clusters in object
      self.col_clusters = col.compute()
```
And similarly for the other Dask method and for the numpy-based method.

2020-09-01 11:01 UTC, girgink commented
Hi @fnattino , I think if initialization is corrected then error and previous clusters can be kept, so that if new runs do not provide a better clustering the method can return previously calculated clusters (and related error) as the best result. This is a good feature. 

Regarding the number of runs, my suggestion is to either to keep track of the number of runs in a method call (which might be less than the requested number due to convergence - and this is a useful information) or have two separate counters one for the total (global) number of runs and one for the runs in the call. 

For the initial clusters, they should be used only once for the first run, but not for the others. If we use it for all runs then all runs will be identical; hence they will loose their meaning (i.e. being a new starting point). Basically initial clusters makes sense only for a single run.

2020-09-01 11:17 UTC, fnattino commented
Good points! 

I would then go for the two counters - something like `nruns_total` (keeping track of all runs performed, regardless of whether they are converged or not) and `nruns_converged` (number of runs converged in the method call). Maybe is also better to move the `nruns` input argument to the various `run_xxx` methods, since this sets the number or runs requested per method call - what do you think? This would also help to solve the second problem you mention, implementing a check that either the initial values for the clusters are set or `nruns > 1`..

2020-09-01 11:32 UTC, girgink commented
Actually unless there is a reason to decouple clustering `nruns` from the `run_xxx` `nruns` there is no need to make it a separate parameter. Eventually the main task of the `run_xxx` methods is to run clustering method `nruns` time. Do you seen any decoupling need?

One addition to my previous comment: the error should be reset (always) if custom initial clusters are specified.

Can it be better to define a result object with clusters, error value, and other meta data, and return it at the end of the computation instead of individual variables? It may also help better separation of inputs and outputs.

2020-09-01 13:13 UTC, fnattino commented
I meant to move the `nruns` input argument from `Coclustering.__init__` to the (various) `Coclustering.run_with_xxx`, to give more flexibility in setting the number or runs each time the `run_with_xxx` method is called - but I guess it's not really needed.  

Also great to return the result object - I will draft the function right now

2020-09-01 13:57 UTC, fnattino commented
What about having a general result object, which entails the method to write results to a file:

```python
class Results(object):
    def __init__(self):
        self.version = __version__
        self.time = datetime.datetime.now().isoformat()
        self.reset(self)

    def reset(self):
        pass

    def write(self, filename):
        with open(filename, 'w') as f:
            json.dump(self.__class__, f, indent=4)
```

and then inherited result objects, like for co-clustering:

```python
class CoclusteringResults(Results):
    def reset(self):
        self.row_clusters = None
        self.col_clusters = None
        self.error = None
        self.nruns_total = 0
        self.nruns_converged = 0
```
which is initialised in the `Coclustering`:

```python
class Coclustering(object):
  def __init__(self, ...):
    self.results = CoclusteringResults()
```
The various `run_with_xxx` methods update the variables in the `cc.results` instance (e.g. `cc.results.error`, `cc.results.col_clusters` and `cc.results.row_clusters`, etc.), they call `cc.results.write()` to serialise results to file, and they finally return the `results` to the user?

2020-09-01 14:56 UTC, girgink commented
It is really nice like this! In this way `run_xxx` methods can also get a result object as a parameter and continue calculations from the previous stop point (e.g. unconverged run, enforced stop, etc.) easily, if required. It is also easier for the end users to deal with a single result object, instead of various variables.

I can also suggest to add metadata related to clustering parameters (e.g. requested number of clusters, iterations, runs, etc.) and method (e.g. numpy/dask, # threads, etc.), which will allow complete visualisation of the computation only by using the result object.

2020-09-01 16:57 UTC, fnattino commented
@girgink  I have created a starting point for the result object, with the initial clusters (if provided) and all output quantities. 

The problem of the cluster initialisation should be solved (only `nruns=1` is accepted if both col and row clusters are given in input) and otherwise all runs are properly randomly initialised. 

Let me know what your thoughts are. Maybe we can merge it first and start using this version on the datasets - then we can expand the values in the results object in a future PR.

2020-09-02 13:38 UTC, girgink commented
Hi @fnattino , thanks a lot! I think they all look good. I agree that it is better to merge and expand later.

2020-09-02 13:39 UTC, fnattino commented
Great, thanks for having a look. I will merge then, and then open an issue to remember.

2020-09-02 13:40 UTC, merged