Check memory requirements
phenology/cgc pull request #33
Opened 2021-06-23 16:57 UTC by rogerkuou

Add memory usage estimation function for `cgc.coclustering_numpy`.

Need to check:

- [ ] Is there an OS dependency to spin up the `memory profiler?

2021-06-25 09:19 UTC, fnattino requested changes
Hi @rogerkuou , great work thanks! Left few comments, let me know if anything is unclear!

2021-06-25 09:19 UTC, fnattino commented on examples/memory_estimation.ipynb
> +{
Nice! I have tried to run it on my laptop, I also see the issue with the first run being a bit "off". I would actually keep a single set of matrix sizes/cluster parameters (right now the first set of parameters is repeated twice), and add one line suggesting to run the cell twice if the result for the first set of parameters is a bit off, probably due to some initialisations within memory_profiler.. 

Minor point: I have also noticed the `sys` package is used but not imported.

2021-06-25 09:20 UTC, fnattino commented
Uh, by the way, we should first merge with `development` before `master`..

2021-06-28 19:19 UTC, rogerkuou commented
Hi @fnattino, thx for the review! I have made changes according to your suggestion. I found there is one issue with `math.product` which is not supported by Python 3.7. Shall we keep Python 3.7 compatible?

2021-06-28 20:17 UTC, fnattino commented
Hi @rogerkuou , thanks! Indeed, I have notice the issue. Let's maybe use `numpy.prod`, which I think should do the work?

2021-06-29 07:45 UTC, fnattino approved these changes

2021-06-29 07:51 UTC, merged